import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Music2, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAppState } from "@/lib/app-state";
import { useT } from "@/lib/i18n";

export const Route=createFileRoute("/music")({head:()=>({meta:[{title:"Music — Felar’s Studies"},{name:"description",content:"Persistent local music and YouTube playback."},{property:"og:title",content:"Music — Felar’s Studies"},{property:"og:description",content:"A calm persistent study soundtrack."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Music});
function Music(){const {state,update}=useAppState();const t=useT();const [url,setUrl]=useState("");const load=()=>{const video=url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{11})/)?.[1];const query=url.includes("?")?url.slice(url.indexOf("?")+1):url;const playlist=new URLSearchParams(query).get("list");const source=playlist?`playlist:${playlist}`:video;if(source)update(store=>({...store,music:{...store.music,current:"youtube",youtubeId:source,playing:true,hidden:false}}))};const embedSource=state.music.youtubeId.startsWith("playlist:")?`https://www.youtube-nocookie.com/embed/videoseries?list=${encodeURIComponent(state.music.youtubeId.slice(9))}&autoplay=1`:`https://www.youtube-nocookie.com/embed/${state.music.youtubeId}?autoplay=1`;return <div className="page"><header className="page-heading"><p className="terminal-kicker">AUDIO / PLAYER</p><h1>{t("music")}</h1><p>{t("youtubeHint")}</p></header><section className="now-playing"><div className="album-art undertale-album"><Music2/><span>HOTEL<br/><small>UNDERTALE</small></span></div><div><p className="eyebrow">{t("builtIn")}</p><h2>{t("hotelTrack")}</h2><p>Toby Fox · UNDERTALE Soundtrack</p><Button onClick={()=>update(store=>({...store,music:{...store.music,current:"hotel",playing:true,hidden:false}}))}><Play/>{t("play")}</Button></div></section><section className="youtube-panel"><p className="terminal-kicker">YOUTUBE / DIRECT LINK</p><h2>{t("youtube")}</h2><div className="url-row"><Input value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://youtube.com/playlist?list=..."/><Button onClick={load}>{t("load")}</Button></div><p>{t("youtubeDirect")}</p>{state.music.current==="youtube"&&state.music.youtubeId&&<div className="video-shell"><iframe title="YouTube" src={embedSource} allow="autoplay; encrypted-media" allowFullScreen/></div>}</section></div>}