import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bookmark, ChevronLeft, ChevronRight, Eye, EyeOff, Heart, Maximize, Minus, Plus, Search, Sparkles, Utensils, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getDocument } from "@/lib/documents";
import { useAppState } from "@/lib/app-state";
import { useT } from "@/lib/i18n";
import { PetAvatar } from "@/components/app/PetAvatar";
import { playSfx } from "@/lib/sfx";

export const Route=createFileRoute("/reader/$documentId")({head:({params})=>({meta:[{title:`Read ${params.documentId} — Felar’s Studies`},{name:"description",content:"Read the original study book inside Felar’s private library."},{property:"og:title",content:"Reading Library — Felar’s Studies"},{property:"og:description",content:"Original study books in a calm, focused reading space."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Reader});
type PageRecord={page:number;topic:string;text:string};
type BookManifest={id:string;pages:PageRecord[]};
const pageUrl=(id:string,page:number)=>`/stuff/books/${id}/${String(page).padStart(4,"0")}.jpg`;

function Reader(){
 const {documentId}=Route.useParams();const doc=getDocument(documentId);const {state,update}=useAppState();const t=useT();const wrapRef=useRef<HTMLDivElement>(null);
 const [page,setPage]=useState(state.library.lastPageByDocument[documentId]??1);const [scale,setScale]=useState(1);const [query,setQuery]=useState("");const [manifest,setManifest]=useState<BookManifest|null>(null);const [imageReady,setImageReady]=useState(false);const [explaining,setExplaining]=useState(false);const [petVisible,setPetVisible]=useState(true);const [petMessage,setPetMessage]=useState("");
 useEffect(()=>{if(!doc)return;let active=true;fetch(`/stuff/books/${doc.id}/manifest.json`).then(r=>r.ok?r.json():Promise.reject()).then((data:BookManifest)=>{if(active)setManifest(data)}).catch(()=>{if(active)setManifest({id:doc.id,pages:[]})});return()=>{active=false}},[doc?.id]);
 useEffect(()=>{if(!doc)return;setImageReady(false);if(state.settings.rememberPage)update(s=>({...s,library:{...s.library,lastOpenedDocument:doc.id,lastPageByDocument:{...s.library.lastPageByDocument,[doc.id]:page}}}));[page-1,page+1].filter(p=>p>0&&p<=doc.pages).forEach(p=>{const image=new Image();image.src=pageUrl(doc.id,p)})},[page,doc?.id,state.settings.rememberPage]);
 useEffect(()=>{if(!doc)return;const onKey=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement)return;if(event.key==="ArrowRight"||event.key==="PageDown")setPage(p=>Math.min(doc.pages,p+1));if(event.key==="ArrowLeft"||event.key==="PageUp")setPage(p=>Math.max(1,p-1))};addEventListener("keydown",onKey);return()=>removeEventListener("keydown",onKey)},[doc?.pages]);
 const current=manifest?.pages[page-1];const searchMatches=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();if(!needle||!manifest)return[];return manifest.pages.filter(p=>p.text.toLocaleLowerCase().includes(needle)).slice(0,8)},[manifest,query]);
 if(!doc)return <div className="page"><h1>Document not found</h1></div>;
 const bookmarks=state.library.bookmarks[doc.id]??[];const toggleBookmark=()=>update(s=>({...s,library:{...s.library,bookmarks:{...s.library.bookmarks,[doc.id]:bookmarks.includes(page)?bookmarks.filter(p=>p!==page):[...bookmarks,page]}}}));const interact=(message:string)=>{playSfx("pet",state);setPetMessage(message);setTimeout(()=>setPetMessage(""),1800)};
 return <div className="reading-room" ref={wrapRef}>
  <div className="reading-aurora" aria-hidden="true"/><header className="reading-header"><Button asChild variant="ghost" size="icon"><Link to="/library" aria-label={t("back")}><ArrowLeft/></Link></Button><div className="reader-title"><strong>{t(doc.subject)} · {t(`part${doc.part}`)}</strong><small>{current?.topic||doc.filename}</small></div><div className="reading-actions"><Button variant="ghost" size="icon" onClick={()=>setPetVisible(v=>!v)} aria-label={petVisible?t("petHide"):t("petShow")}>{petVisible?<EyeOff/>:<Eye/>}</Button><Button variant="ghost" size="icon" onClick={toggleBookmark} className={bookmarks.includes(page)?"active-icon":""} aria-label={t("bookmark")}><Bookmark/></Button><Button variant="ghost" size="icon" onClick={()=>wrapRef.current?.requestFullscreen()} aria-label={t("fullscreen")}><Maximize/></Button></div></header>
  <main className="book-stage"><div className="book-page-shell" style={{"--book-scale":scale} as React.CSSProperties}>{!imageReady&&<div className="page-shimmer" aria-hidden="true"/>}<img key={`${doc.id}-${page}`} className={imageReady?"book-page-image is-ready":"book-page-image"} src={pageUrl(doc.id,page)} alt={`${t(doc.subject)}, ${t(`part${doc.part}`)}, ${t("page")} ${page}`} onLoad={()=>setImageReady(true)}/></div></main>
  <div className="reader-search-float"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("search")}/>{searchMatches.length>0&&<div className="search-results">{searchMatches.map(result=><Button key={result.page} variant="ghost" onClick={()=>{setPage(result.page);setQuery("")}}><span>{String(result.page).padStart(3,"0")}</span>{result.topic}</Button>)}</div>}</div>
  <Button className="jarvis-explain-button" variant="secondary" onClick={()=>setExplaining(true)}><Sparkles/>JARVIS · {t("explainPage")}</Button>
  {petVisible&&<aside className="reader-pet reader-pet-quiet"><div className="pet-bubble">{petMessage}</div><PetAvatar type={state.pet.type} size="tiny" equipped={state.pet.equippedItems} onInteract={()=>interact("♥")}/><div><Button size="icon" variant="ghost" onClick={()=>interact("♥")} aria-label={t("petPet")}><Heart/></Button><Button size="icon" variant="ghost" onClick={()=>interact("♪")} aria-label={t("petFeed")}><Utensils/></Button></div></aside>}
  {explaining&&<div className="jarvis-explain" role="dialog" aria-modal="true"><section className="jarvis-terminal animate-enter"><header><p>JARVIS // PAGE {String(page).padStart(3,"0")}</p><Button variant="ghost" size="icon" onClick={()=>setExplaining(false)} aria-label={t("close")}><X/></Button></header><h2>{current?.topic||`${t(doc.subject)} · ${t(`part${doc.part}`)}`}</h2><p className="prompt">&gt; {t("pageOverview")}</p><div className="jarvis-page-copy">{current?.text?current.text.split("\n").slice(0,12).map((line,index)=><p key={`${index}-${line}`}>{line}</p>):<p>{t("pageExplanation")}</p>}</div></section></div>}
  <footer className="reading-dock"><Button variant="ghost" size="icon" onClick={()=>setPage(p=>Math.max(1,p-1))} aria-label="Previous page"><ChevronLeft/></Button><Input aria-label={t("page")} type="number" min={1} max={doc.pages} value={page} onChange={e=>setPage(Math.max(1,Math.min(doc.pages,Number(e.target.value))))}/><span>/ {doc.pages}</span><input className="page-scrubber" aria-label="Page position" type="range" min={1} max={doc.pages} value={page} onChange={e=>setPage(Number(e.target.value))}/><Button variant="ghost" size="icon" onClick={()=>setPage(p=>Math.min(doc.pages,p+1))} aria-label="Next page"><ChevronRight/></Button><span className="reader-divider"/><Button variant="ghost" size="icon" onClick={()=>setScale(s=>Math.max(.7,s-.1))} aria-label="Zoom out"><Minus/></Button><span>{Math.round(scale*100)}%</span><Button variant="ghost" size="icon" onClick={()=>setScale(s=>Math.min(1.8,s+.1))} aria-label="Zoom in"><Plus/></Button></footer>
 </div>
}
