import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ChevronDown, EyeOff, Grip, Music2, Pause, Play, SkipBack, SkipForward, Volume2, VolumeX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { useAppState } from "@/lib/app-state";
import { useT } from "@/lib/i18n";

export function MusicPlayer(){
 const {state,update}=useAppState();const t=useT();const audio=useRef<HTMLAudioElement>(null);const [progress,setProgress]=useState(0);const drag=useRef<{x:number;y:number;left:number;bottom:number}|null>(null);
 const setMusic=(patch:Partial<typeof state.music>)=>update(store=>({...store,music:{...store.music,...patch}}));
 useEffect(()=>{const player=audio.current;if(!player)return;player.volume=state.music.muted?0:state.music.volume;if(state.music.current==="hotel"){if(state.music.playing)void player.play().catch(()=>{});else player.pause()}},[state.music.playing,state.music.volume,state.music.muted,state.music.current]);
 useEffect(()=>{const move=(event:PointerEvent)=>{if(!drag.current)return;const x=Math.max(8,Math.min(innerWidth-64,drag.current.left+event.clientX-drag.current.x));const y=Math.max(76,Math.min(innerHeight-64,drag.current.bottom-(event.clientY-drag.current.y)));setMusic({position:{x,y}})};const stop=()=>{drag.current=null};addEventListener("pointermove",move);addEventListener("pointerup",stop);return()=>{removeEventListener("pointermove",move);removeEventListener("pointerup",stop)}},[]);
 const youtubeSource=state.music.youtubeId.startsWith("playlist:")?`https://www.youtube-nocookie.com/embed/videoseries?list=${encodeURIComponent(state.music.youtubeId.slice(9))}&autoplay=${state.music.playing?1:0}&controls=0`:`https://www.youtube-nocookie.com/embed/${state.music.youtubeId}?autoplay=${state.music.playing?1:0}&controls=0`;
 if(state.music.hidden)return <Button className="music-restore" size="icon" onClick={()=>setMusic({hidden:false,minimized:true})} aria-label={t("showMusic")}><Music2/></Button>;
 return <><audio ref={audio} src="/stuff/audio/hotel.mp3" loop onTimeUpdate={event=>setProgress(event.currentTarget.currentTime/(event.currentTarget.duration||1)*100)} onEnded={()=>setMusic({playing:false})}/>{state.music.current==="youtube"&&state.music.youtubeId&&<iframe className="youtube-audio-frame" title="YouTube player" src={youtubeSource} allow="autoplay"/>}{state.music.minimized?<div className="music-orb" style={{left:state.music.position.x,bottom:state.music.position.y}} onPointerDown={event=>{drag.current={x:event.clientX,y:event.clientY,left:state.music.position.x,bottom:state.music.position.y};event.currentTarget.setPointerCapture(event.pointerId)}}><Button size="icon" onClick={()=>setMusic({playing:!state.music.playing})} aria-label={state.music.playing?t("pause"):t("play")}>{state.music.playing?<Pause/>:<Music2/>}</Button><Button className="music-orb-expand" variant="ghost" size="icon" onClick={()=>setMusic({minimized:false})} aria-label={t("expandMusic")}><Grip/></Button></div>:<div className="player-bar"><Link to="/music" className="track"><span className="album-glyph"><Music2/></span><span><strong>{state.music.current==="hotel"?t("hotelTrack"):"YouTube"}</strong><small>{state.music.current==="hotel"?"Toby Fox · UNDERTALE Soundtrack":state.music.youtubeId}</small></span></Link><div className="player-controls"><Button variant="ghost" size="icon" aria-label={t("previous")}><SkipBack/></Button><Button size="icon" aria-label={state.music.playing?t("pause"):t("play")} onClick={()=>setMusic({playing:!state.music.playing})}>{state.music.playing?<Pause/>:<Play/>}</Button><Button variant="ghost" size="icon" aria-label={t("next")}><SkipForward/></Button></div><div className="player-volume"><Button variant="ghost" size="icon" aria-label={t("volume")} onClick={()=>setMusic({muted:!state.music.muted})}>{state.music.muted?<VolumeX/>:<Volume2/>}</Button><Slider value={[state.music.volume*100]} onValueChange={value=>setMusic({volume:(value[0]??45)/100})}/></div><div className="player-window-actions"><Button variant="ghost" size="icon" onClick={()=>setMusic({minimized:true})} aria-label={t("shrinkMusic")}><ChevronDown/></Button><Button variant="ghost" size="icon" onClick={()=>setMusic({hidden:true})} aria-label={t("hideMusic")}><EyeOff/></Button></div><span className="player-progress" style={{width:`${progress}%`}}/></div>}</>
}