/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PetRouteImport } from './routes/pet'
import { Route as ReaderDocumentIdRouteImport } from './routes/reader.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderDocumentIdRoute = ReaderDocumentIdRouteImport.update({
  id: '/reader/$documentId',
  path: '/reader/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/pet': typeof PetRoute
  '/reader/$documentId': typeof ReaderDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/pet': typeof PetRoute
  '/reader/$documentId': typeof ReaderDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/music': typeof MusicRoute
  '/notes': typeof NotesRoute
  '/pet': typeof PetRoute
  '/reader/$documentId': typeof ReaderDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/library' | '/music' | '/notes' | '/pet' | '/reader/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/music' | '/notes' | '/pet' | '/reader/$documentId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/music'
    | '/notes'
    | '/pet'
    | '/reader/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  MusicRoute: typeof MusicRoute
  NotesRoute: typeof NotesRoute
  PetRoute: typeof PetRoute
  ReaderDocumentIdRoute: typeof ReaderDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$documentId': {
      id: '/reader/$documentId'
      path: '/reader/$documentId'
      fullPath: '/reader/$documentId'
      preLoaderRoute: typeof ReaderDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  MusicRoute: MusicRoute,
  NotesRoute: NotesRoute,
  PetRoute: PetRoute,
  ReaderDocumentIdRoute: ReaderDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
